Project.toml
src/JSServe.jl

Setting `ENV["JSSERVE_LISTEN_URL"] = "0.0.0.0"` before using JSServe lets you change the url the server is listening to.

add JSSERVE_LISTEN_URL to switch listen url

---

src/display.jl

...so that it actually picks up the deps of the rendered DOM

reorder import to be after render

---

src/widgets.jl
test/markdown.jl

This does a couple of simple fixes to the markup of buttons and tables.
For buttons, `<input type=button/>` does not exist, with this PR JSServe generates the `<button>` tag instead. Main difference is that when you style it with for example Tailwind, as in:
```julia
app = App() do
btn = Button("Click here!", class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded")
return DOM.div(JSServe.TailwindCSS, btn)
end
```
you get the nice "hand-shaped cursor" when hovering on the button.
For tables, it replaces `th` (table header) with `td` (table data) for data rows, so they are not rendered in bold by default (only the header is).

html fixes for tables and buttons

---

src/browser_display.jl
test/various.jl

Fix #98 by using `tryrun`, which does not throw and returns `false` if something goes wrong (either external process cannot be started or it returns error).
On a related note, do we also want to make it customizable whether JSServe tries to open the browser? I'm using `display(app)` to start serving an app on tmux, and I don't necessarily want the server to try and open a browser (but maybe I'm doing things the wrong way and there is another command to just start serving).

safer openurl

---

src/JSServe.jl
src/server.jl

This PR enables the use of hostnames such as "localhost" and removes the reliance on ipv4 by utilizing getaddrinfo instead of parsing an IPv4 address.

remove reliance on 127.0.0.1 and other ipv4 addresses

---

src/display.jl

The key difference is that the helper `Hyperscript.wraphtml` also sets the `DOCTYPE` in the html page, see [here](https://github.com/JuliaWeb/Hyperscript.jl/blob/0ef32362062c580077020a85ca6edaec7dbdc1b8/src/Hyperscript.jl#L500).
If we don't want to depend on a Hyperscript helper function, I imagine something like
```julia
sprint() do io
println(io, "<!doctype html>")
show(io, MIME"text/html"(), Hyperscript.Pretty(html_body))
end
```
would also work.
UPDATE: I've actually moved away from `wraphtml` because it was "double-wrapping" in the `<html>` tag and am simply adding the doctype by hand

set doctype in page

---

src/display.jl
src/session.jl

... To avoid user interaction, without JS being fully initialized

hide dom during setup

---

examples/basics.jl
examples/serve.jl
src/server.jl
src/types.jl

Provide an official way to wait on the server event loop.
Based on discourse post https://discourse.julialang.org/t/a-headless-non-interactive-jsserve-and-wglmakie-server/90549

add Base.wait(::Server)

---

.vscode/extensions.json
.vscode/settings.json
js_dependencies/JSServe.js
tsconfig.json

TSConfig removes guesswork from VS Code about which types are available, it is currently set to "this will run in a modern browser".
This currently mostly gives some null errors, you could fix those (yay), or disable them by setting `"strictNullChecks"` to `false`.
The Deno VS Code extension provides typings for your CDN imports. The means that something like `Pako.deflate` gives types/documentation on hover, and it can be type checked as part of your code.
In Pluto we also set up CI to run the TSC checks (with null checks disabled), which is nice for new contributors: https://github.com/fonsp/Pluto.jl/blob/main/.github/workflows/TypeScriptCheck.yml

setup TSConfig and Deno extension

---

examples/serve.jl

Updating from 1.2 to 2.0 caused me some confusion (my reverse proxy stopped working), so I thought mentioning this might be helpful for others.

mention `proxy_url` in the serve.jl example

---

src/server-defaults.jl

Per https://github.com/SimonDanisch/JSServe.jl/blob/master/src/server-defaults.jl#L153.

fix default `listen_port` arg in docstring

---

js_dependencies/markdown.css
src/HTTPServer/implementation.jl
src/JSServe.jl
src/asset-serving/asset.jl
src/asset-serving/http.jl
src/asset-serving/no-server.jl
src/export.jl
src/interactive.jl
src/js_source.jl
src/rendering/hyperscript_integration.jl
src/rendering/jsrender.jl
src/rendering/markdown_integration.jl
src/tailwind-dashboard.jl
src/types.jl

Enables workflow like this:
```julia
using Revise, JSServe, Markdown
import JSServe.TailwindDashboard as D
includet("src/html-classes.jl")
includet("src/index.jl")
includet("src/github.jl")
includet("src/support.jl")
includet("src/team.jl")
includet("src/contact.jl")
routes, task, server = interactive_server([asset_path(), joinpath(@__DIR__, "src")]) do
return Routes(
"/" => index,
"/team" => team,
"/contact" => contact,
"/support" => support
)
end
```
See: https://github.com/MakieOrg/Website/blob/sd/jsserve/make.jl#L1-L21

Improvements for static export workflow

---

js_dependencies/JSServe.bundled.js
js_dependencies/JSServe.js
js_dependencies/Protocol.js
src/HTTPServer/HTTPServer.jl
src/HTTPServer/helper.jl
src/HTTPServer/implementation.jl
src/asset-serving/asset.jl
src/asset-serving/http.jl
src/types.jl
test/connection-serving.jl
test/subsessions.jl

When I introduced BinaryAsset, which can also be served from the `HTTPAssetServer` much like `ES6Module`, gc'ing `assetserver.registered_files` became mandatory to not accumulate lots of binary assets.
I just gave every session its own assetserver to make cleanup easier, which makes `ES6Module` have different URLs, even for a child session - which practically disables the browsers caching for `import(url)`, which we rely on to not needing to manage imports ourselves.
This PR switches to reference counting, so that assets in one browser tab always have the same urls.

use actual reference counting for HTTPAssetServer

---

src/HTTPServer/helper.jl
src/serialization/caching.jl

For long standing sessions as is the case with `BrowserDisplay` or in notebooks/vscode, deregister callbacks would accumulate unbounded, since they would be added to the root session, which will never be freed.
This little change adds them to the correct child session, so they get freed properly.
This shouldn't concern the server use case, as a new root session is created for every request.
Also adds an error conversion, that I forgot to push, which improves error display in certain edge cases.

Fix memory leak with DisplayHandler

---

docs/src/deployment.md
src/HTTPServer/browser-display.jl

This PR introduces a new keyword argument for `JSServe.use_electron_display`: calling
```
use_electron_display(devtools = false)
```
avoids opening the Developer Tools panel in the newly created Electon window. The default behavior (when no argument is specified) is unchanged.
The PR also documents how to toggle the devtools panel for an already created Electron Display.
Does this need explicit testing in your opinion? I'm not sure exactly how to test that an Electron window has its devtools panel open or not...
Fixes: #184

Option to disable the devtools panel when creating Electron windows

---

src/rendering/hyperscript_integration.jl

fixes:
```julia
function img2binary(img)
io = IOBuffer()
show(io, MIME"image/png"(), img)
return Bonito.BinaryAsset(take!(io), "image/png")
end
App() do app
img_array = FileIO.load("...")
DOM.img(src=img2binary(img_array))
end
```

fix attributes with binary asset (e.g. DOM.img)

---

src/js_source.jl
test/various.jl

This commit carves out a specific exception for "${...}" which is never a useful interpolation from the Julia side (it always errors since `{...}` is a deprecated syntax) and is a template literal placeholder on the Javascript side.
The D3.js examples use this feature heavily, and this small fix is enough to get them working as `js"..."` strings.
There remain other interpolation issues for, e.g., jQuery which uses `$` as a magic global (e.g. `$("button.continue").html("Next Step...")`), but fixing those would be a breaking change to syntax.

Exclude JS template literal placeholders "${...}" from interpolation

---

docs/src/deployment.md
src/HTTPServer/implementation.jl

closes https://github.com/SimonDanisch/Bonito.jl/issues/220
with these changes, an HTTPS protocol is possible with:
```
sslconfig = MbedTLS.SSLConfig(<path-to-SSL-certificate-file>,<path-to-SSL-key-file>)
Bonito.Server(main, url, port, sslconfig=sslconfig)
```
however!  more work is needed, as the URL to assets still uses "http://", and so they fail to load.  somehow the `protocol` kwarg [here](https://github.com/SimonDanisch/Bonito.jl/blob/master/src/HTTPServer/implementation.jl#L142) needs to know if SSL is being used.  not sure yet how to do that...

add support for secure connections

---

src/asset-serving/asset.jl
src/asset-serving/no-server.jl
src/session.jl

We need to create imports in the header, to be sure that they exist before e.g. `onjs`.
Closes https://github.com/SimonDanisch/Bonito.jl/issues/223

fix imports in js with NoServer

---

docs/src/deployment.md
src/HTTPServer/implementation.jl

`HTTP.listen` has an `access_log` argument.  not sure why, but passing it into `HTTP.Servers.Listener` doesn't work.
the other commit in this PR simply fixes the carriage returns, and replaces some tabs with spaces.

enable logging requests

---

docs/src/deployment.md

the old name of this package was still referenced (and misspelled!) in the docs...

change one more JSServer to Bonito

---

js_dependencies/Bonito.bundled.js
js_dependencies/Observables.js
test/basics.jl

On  the main branch, the `if` clause before updating the value on JS will prevent the update when `value` is "falsy" (`0`, `""`, `null`, etc).
Simplest way to test is to run
```julia
using Bonito
obs = Observable(1)
app = App() do session
evaljs(session, js"""
$obs.notify(0, true);
console.log($obs.value)
""")
end
```
on main, the console log shows `1` (no update occurred) and on this PR it shows `0`.
I wonder whether the idea was to allow `obs.notify()`, intending to not update the observable and only trigger callbacks but
- that should probably be done with `value !== undefined`
- on master that also doesn't work, as the julia observable gets updated with `nothing`.

notify also on falsy values

---

docs/src/extending.md
src/connection/connection.jl
src/connection/websocket-handler.jl
src/connection/websocket.jl

Previously outlined here: https://github.com/SimonDanisch/Bonito.jl/issues/244

Add `WebSocketHandler` helper for websocket-based FrontendConnection extensions

---

docs/src/extending.md
src/connection/websocket.jl
test/connection-serving.jl

The idea here is that
1. People can customize the websocket cleanup behavior in Bonito
2. Those wanting to manage their own websockets can make use of the same pluggable behaviour including using the default policy from Bonito.
Builds on https://github.com/SimonDanisch/Bonito.jl/pull/247

Add websocket cleanup policy

---

src/Bonito.jl
src/connection/websocket.jl

To e.g. not make precompile hang, if it happens to open a server (which would already happen for `Session()`).

clean up possible open tasks on exit

---

src/asset-serving/asset-serving.jl

Otherwise any runtime usage of `depedency_path` won't have access to the source files.
https://github.com/SimonDanisch/Bonito.jl/blob/cd9583508a6a875ca08d48dc50095a138c503eb7/src/widgets.jl#L420 is the only call site that would be effected by it. The other current usage is all globals, which end up creating separate relocatable files for each rather than reusing the `JS_DEPENDENCIES` one. Would need a fair bit of changes to avoid that, and probably doesn't matter too much, it's not that much extra data being store in the module.

Store `@path` for `js_dependencies` in a module const

---

src/app.jl
src/rendering/observables.jl
src/serialization/caching.jl
src/session.jl

Root sessions wouldn't free a `Retain(Observable())` even when closed, accumulating updates + messages even after the session got closed for good.
This PR introduces more `isclosed` checks and errors to avoid this situation, and also cleans up Retain on close of a root session.

More sanity checks for closed root sessions and freeing Retains for them

---

src/HTTPServer/helper.jl
src/HTTPServer/implementation.jl
src/app.jl

```julia
App() do 
error("error")
end
```
Would show an unreadable error and hang, since it was waiting for the session.
This cleans up the error display and makes sure it doesn't wait on the session anymore.

throw better errors when app errors and fix hang

---

src/asset-serving/asset.jl
test/runtests.jl
test/test-bundles.jl

I think github cloning messes with the time stamps of the files, so `needs_bundling` may return true when checked out, and on a read only file system that would lead to a warning even if everything works as expected.

turn warn into debug

---

src/server-defaults.jl

This adds [base_url](https://jupyterhub.readthedocs.io/en/latest/reference/api/app.html#jupyterhub.app.JupyterHub.base_url) to the jupyterlab proxy_url. By default, base_url = "/" which provides the same behavior. If base_url is different, then the proxy_url should change to reflect this.
to test:
One can recreate the same issue with just the julia-notebook container. Run it interactively to skip the startup script
```
docker run -p 8888:8888 -it quay.io/jupyter/julia-notebook:python-3.12 /bin/bash
```
start jupyter-lab and modify ServerApp.base_url
```
jupyter lab --no-browser --ServerApp.base_url="ipython"
```
open the link in your brower, run the commands in the image and get a websocker error
With this branch the websocket error disappears and pan/zoom works in the scatter plot.

jupyter_lab: include base_url in proxy_url

---

src/widgets.jl

`merge(a,b)` will have the entries from the `b` in precedence over `a`. The way it's written right now, user options are overwritten by `defaults` (and thus ignored)
```julia
julia> merge(Dict(1=>2), Dict(1=>4))
Dict{Int64, Int64} with 1 entry:
1 => 4
```
This commit fixes that.

Fix CodeEditor option handling

---

docs/src/index.md

```julia
julia> r"*"
ERROR: LoadError: PCRE compilation error: quantifier does not follow a repeatable item at offset 0
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] compile(pattern::String, options::UInt32)
@ Base.PCRE ./pcre.jl:165
[3] compile(regex::Regex)
@ Base ./regex.jl:80
[4] Regex(pattern::String, compile_options::UInt32, match_options::UInt32)
@ Base ./regex.jl:40
```

Fix Regex in doc

---

src/js_source.jl

This fixes another lookup failure.
Hopefully the last one :)

lock, so binary fetches are in correct order

---

src/app.jl
src/session.jl
src/types.jl

This PR tries two things:
- do not wrap `Assets` in `<head>` in `<div>` as this seems to be invalid HTML
- in browser display, don't combine parent init and sub init in a div but instead render the sub init DOM and put the parent init fragment as the first body node

Attemt to fix DOM

---

src/server-defaults.jl

Two-argument `get()` is not defined, so we use direct indexing instead.

Fix `jupyterlab_proxy_url()`

---

js_dependencies/Websocket.bundled.js
js_dependencies/Websocket.js
src/HTTPServer/implementation.jl
src/asset-serving/http.jl
src/connection/dual-websocket.jl
src/connection/websocket.jl
src/server-defaults.jl
test/connection-serving.jl

This sets the proxy_url by default to `""`, which then makes the websocket connection use `window.href` as a base while the the http asset_server uses `HTTPServer.relative_url(server, address...)`, which appends the proxy_url only if set and otherwise leaves it at `./`. This means in most setups, one doesn't need to set `proxy_url` anymore.
One still needs to set it, if the route for reaching the bonito server is completely different, e.g. if it's proxied as for JuliaHub, or other more complex nginx setups etc.

make it less necessary to set proxy_url

---

src/session.jl

When multiple child session contain the same asset it will be included nchildren times.
After rendering it for the first time, we can add it to the root session to not render it again

add asset to root session to not include it again

---

src/HTTPServer/implementation.jl
src/app.jl
src/asset-serving/http.jl
src/connection/dual-websocket.jl
src/connection/no-connection.jl
src/connection/pluto.jl
src/connection/sub-connection.jl
src/connection/websocket-handler.jl
src/connection/websocket.jl
src/rendering/observables.jl
src/serialization/caching.jl
src/serialization/msgpack.jl
src/serialization/serialization.jl
src/serialization/types.jl
src/session.jl
src/types.jl
test/basics.jl

Factor out the SerilizedMessage -> BinaryMessage refactor from: Moves back the work of going from dict -> binary for send(connection, msg), so that it can be done in the websocket handler
So this PR only cleans up sending large_write, and only serializing to the Dict form for any message (especially queued messages), instead of going full binary. Binary serialization is left to the connection.
The connection can now optionally accept `SerializedMessage` by overloading ` write(::Connection, ::SerializedMessage)`.

serialized message refactor
